"""Rebuild references/effects.md from the `// key: value` headers of shaders/*.sksl.

    python3 scripts/catalog.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
KIND_ORDER = ["generator", "overlay", "filter", "mask"]
KIND_TITLE = {
    "generator": "Generators: draw their own pixels (backgrounds, fills clipped to shapes)",
    "overlay": "Overlays: composite over SVG with the listed mix-blend-mode",
    "filter": "Filters: process an image or video frame bound to uSrc",
    "mask": "Masks: alpha coverage for wipes and dissolves (drive uProgress 0 to 1)",
}


def header(path):
    out = {"uniform": []}
    for line in path.read_text().splitlines():
        if not line.startswith("//"):
            break
        m = re.match(r"//\s*(\w+):\s*(.*)", line)
        if not m:
            # continuation lines of `about:` / `note:`
            last = out.get("_last")
            if last and line.strip("/ ").strip():
                out[last] += " " + line.strip("/ ").strip()
            continue
        key, value = m[1], m[2].strip()
        if key == "uniform":
            out["uniform"].append(value)
            out["_last"] = None
        else:
            out[key] = value
            out["_last"] = key if key in ("about", "note") else None
    return out


def main():
    effects = [(p, header(p)) for p in sorted((ROOT / "shaders").glob("*.sksl"))]
    lines = [
        "# Effect catalog",
        "",
        f"{len(effects)} effects. Generated by `scripts/catalog.py` from the shader headers; do not edit by hand.",
        "Every uniform is listed with its default. `iResolution`, `iTime`, `uSrc` and `uSrcSize` are filled",
        "by fframes / `fx.rs`. Ported from shader-effects-inc/shaders (MIT) unless the `from:` line says otherwise.",
        "",
    ]
    for kind in KIND_ORDER:
        group = [(p, h) for p, h in effects if h.get("kind", "").split()[0:1] == [kind]]
        if not group:
            continue
        lines += [f"## {KIND_TITLE[kind]}", ""]
        for p, h in group:
            blend = f" · blend `{h['blend'].split()[0]}`" if h.get("blend") else ""
            lines.append(f"### {h.get('fx', p.stem)}{blend}")
            lines.append(f"`shaders/{p.name}`. {h.get('about', '').strip()}")
            if h["uniform"]:
                lines.append("")
                lines.append("uniforms: " + ", ".join(f"`{u}`" for u in h["uniform"]))
            if h.get("note"):
                lines.append("")
                lines.append(f"note: {h['note']}")
            lines.append("")
    (ROOT / "references" / "effects.md").write_text("\n".join(lines))
    print(f"references/effects.md: {len(effects)} effects")


if __name__ == "__main__":
    main()
